name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Rubocop
        run: bundle exec standardrb --no-fix

  test:
    needs: [linting]
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0', '3.1' ]
        gemfile:
          - gemfiles/rails_5_2.gemfile
          - gemfiles/rails_6_0.gemfile
          - gemfiles/rails_6_1.gemfile
          - gemfiles/rails_7_0.gemfile
        exclude:
          - ruby: '2.5'
            gemfile: gemfiles/rails_7_0.gemfile
          - ruby: '2.6'
            gemfile: gemfiles/rails_7_0.gemfile

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
